name: Build and push Docker images
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSW }}
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: bikosolutions/developers_repo:latest,bikosolutions/developers_repo:2.0.7
